baseURL = "https://squaredcow.dev/"
languageCode = "en-us"
title = "squaredcow.dev"
theme="cactus"
copyright = "© Luis Vaca"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	description = "As a reader of my sorts, this is me moving towards the world of writing. With time I realized that each new learning takes time from us and the way I see it, the last piece to complete the exchange is to write it down. No more drafts left unfinished! That said, dear reader: Welcome!"
	mainSection = "posts"

# Social Tags

[[params.social]]
name = "email"
link = "luis.vaca@squaredcow.dev" # no need for "mailto:" at the start

[[params.social]]
name = "github"
link = "https://github.com/warcod3r"

[[params.social]]
name = "twitter"
link = "https://twitter.com/warcod3r"

[[params.social]]
name = "linkedin"
link = "https://linkedin.com/in/luivaca"

[[params.social]]
name = "rss"
link = "/index.xml"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Author"
url = "/author"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "License"
url = "/license"
weight = 5